apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eurotrade.serviceAccountName" . }}
  labels:
    {{- include "eurotrade.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
