{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ include "eurotrade.serviceAccountName" . }}

  labels:
    {{- include "eurotrade.labels" . | nindent 4 }}

  annotations:
    azure.workload.identity/client-id: {{ .Values.serviceAccount.annotations.azureWorkloadIdentityClientId | quote }}

automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}